{
    'name': "Real Estate",
    'summary': "Manage real estate properties",
    'description': "Module for managing real estate properties.",
    'author': "Your Name",
    'website': "https://www.yourcompany.com",
    'category': 'Uncategorized',
    'version': '0.1',
    'application': True,
    'depends': ['base'],
    'data': [
        'security/ir.model.access.csv',
        'views/estate_property_offer_views.xml',
        'views/estate_property_type_views.xml',
        'views/estate_menus.xml',
        'views/estate_property_views.xml',
        'views/estate_property_search.xml',
        'views/estate_property_tag_views.xml',
        'views/res_users_views.xml',
    ],
}
